### ISSUE TITLE
works on simulator but not on phone

### ISSUE THREAD

**Issue by utanapishtim** [holepunchto/pear-expo-hello-world#1]
with a little tweaking and updating of dependencies I was able to get everything building and running on the ios simulator but unable to get it running on my iphone using either the `Expo Go` app or building in Xcode. Depending on which method is used the error is different. 

Using xcode to build and run I get:

![iphone-xcode-error](https://github.com/holepunchto/pear-expo-hello-world/assets/9367574/27617615-9d3e-47b8-bfb0-76164a6e23f9)

Using `npx expo run:ios` and then `Expo Go` to open the app, I get:

![iphone-expo-error-1](https://github.com/holepunchto/pear-expo-hello-world/assets/9367574/60312b6f-9b4a-458c-aaed-a18d27ff1893)
![iphone-expo-error-2](https://github.com/holepunchto/pear-expo-hello-world/assets/9367574/c0987685-ace1-40d0-9ec3-b3ff73a46bfe)
![iphone-expo-error-3](https://github.com/holepunchto/pear-expo-hello-world/assets/9367574/d7c12ff9-e29b-4f67-b6df-2d93ed554291)

**Comment by mafintosh** [comment]
cc @iamyellow

**Comment by utanapishtim** [comment]
resolved
