### ISSUE TITLE
Explanation / How Are Things Tied Together

### ISSUE THREAD

**Issue by utanapishtim** [holepunchto/pear-expo-hello-world#2]
@iamyellow @mafintosh 

I am hoping one or both of you could shed some light on how these examples work. Perhaps we could hop in a Keet call and I could screen record the conversation and then open a PR with some docs?

**Comment by iamyellow** [comment]
sure, i have a pending section on the readme explaining how the pieces fall into place.

**Comment by utanapishtim** [comment]
@iamyellow I should have just asked one question 😅 are you saying "sure" to shedding light on how the examples work or hopping on a Keet call?

**Comment by utanapishtim** [comment]
If the latter, I invited you to a private repo with a Keet invite.

**Comment by utanapishtim** [comment]
@iamyellow just checking in on this, even a link to your branch would suffice.

**Comment by utanapishtim** [comment]
Hey @iamyellow just touching base on this again.

**Comment by jermsam** [comment]
@utanapishtim managed to get an explanation?

**Comment by iamyellow** [comment]
Sorry for the delay guys. I still due this... It'd help me a lot if you can list here where you're having a bad time trying to understand so I can focus on that

**Comment by gasolin** [comment]
could check https://github.com/holepunchto/pear-expo-hello-world?tab=readme-ov-file#how-it-works
